add action classes
htmlacademy-yii/2052497-task-force-4 pull request #5
Opened 2022-08-27 21:42 UTC by EMV2298

2022-08-28 02:58 UTC, b1rdex requested changes

2022-08-28 02:58 UTC, b1rdex commented on classes/business/actions/actions.php
> +abstract class Actions {
Этот и другие файлы классов нужно переименовать actions.php -> Actions.php. Иначе не будет работать на регистрозависимой ФС (linux, mac os).

2022-08-28 02:58 UTC, b1rdex commented on classes/business/actions/cancel.php
> +    return 'cancel';
Стоит использовать константы из класса Task: `return Task::ACTION_CUSTOMER_CANCEL;`

2022-08-28 02:58 UTC, b1rdex commented on classes/business/actions/cancel.php
> +class cancel extends Actions {
Cancel

2022-08-28 02:58 UTC, b1rdex commented on classes/business/actions/reject.php
> +class reject extends Actions {
Reject

2022-08-28 02:58 UTC, b1rdex commented on classes/business/actions/take.php
> +class take extends Actions {
Take

2022-08-28 02:58 UTC, b1rdex commented on classes/business/actions/take.php
> +    return $userId === $executorId;
Тут логика немного другая: откликнуться можно если ещё не задан $executorId у задания, соответственно он будет null. И при этом ты должен быть не $customerId.

2022-08-28 02:58 UTC, b1rdex commented on classes/business/task.php
>  class Task {
task.php тоже нужно переименовать в Task.php

2022-08-28 23:02 UTC, EMV2298 commented
Пара лишних коммитов с переименование файлов от того что git не видел разницы между регистрами. Поэтому пришлось менять имя, а потом обратно, чтобы изменения попали в репозиторий

2022-08-29 00:37 UTC, b1rdex approved these changes

2022-08-29 00:37 UTC, b1rdex commented on classes/business/actions/Actions.php
> +    abstract public static function checkAccess(int $userId, int $customerId, int $executorId): bool;
В сигнатуре ещё нужно сделать executor id nullable

2022-08-29 00:38 UTC, merged