install yii-2
htmlacademy-yii/2052497-task-force-4 pull request #8
Opened 2022-09-11 19:23 UTC by EMV2298

2022-09-13 05:45 UTC, b1rdex requested changes
Дополнительно: 1) нужно вернуть scheme.sql и 2) файлы в папке data/

2022-09-13 05:45 UTC, b1rdex commented on views/layouts/main.php
> +    <link rel="stylesheet" href="css/style.css">
1. $this->head()
2. файл стилей регистрируем через $this->registerLinkTag

2022-09-13 05:45 UTC, b1rdex commented on views/layouts/main.php
> +<body>
$this->beginBody()

2022-09-13 05:45 UTC, b1rdex commented on views/layouts/main.php
> +</body>
$this->endBody()

2022-09-13 05:45 UTC, b1rdex commented on views/layouts/main.php
> +    <title>Taskforce</title>
Html::encode($this->title)

2022-09-13 23:39 UTC, EMV2298 commented on views/layouts/main.php
> +    <link rel="stylesheet" href="css/style.css">
При регистрации стилей у меня возникла проблема. Стили bootstrap.css ломали верстку, я не понял зачем они нужны и  закомментировал зависимость от них, теперь все ок. Еще вопрос, можно ли сразу подключить файл стилей  в Классе AppAsset.php?

2022-09-16 11:21 UTC, b1rdex commented on views/layouts/main.php
> +    <link rel="stylesheet" href="css/style.css">
Да, можно через ассеты конечно

2022-09-16 11:22 UTC, merged